version: "3.9"

services:
  backend:
    image: node:20-alpine
    container_name: aws-manager-backend
    working_dir: /app
    volumes:
      - ./backend:/app:z
      - /app/node_modules
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm run start:dev"
    environment:
      - NODE_ENV=development
    networks:
      - aws-manager-net

  frontend:
    image: node:20-alpine
    container_name: aws-manager-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    networks:
      - aws-manager-net

  n8n:
    image: n8nio/n8n:latest
    container_name: aws-manager-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme
      - GENERIC_TIMEZONE=Europe/Madrid
    volumes:
      - ./n8n_data:/home/node/.n8n:z
    networks:
      - aws-manager-net

  postgres:
    image: postgres:15-alpine
    container_name: aws-manager-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=aws_manager
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:z
    networks:
      - aws-manager-net

networks:
  aws-manager-net:
    driver: bridge